name: .NET Hello World build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: labs/continuous-integration/src/HelloWorld
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "6.0.x"

      - name: Restore & build
        run: |
          dotnet restore
          dotnet build

      - name: Run
        run: |
          dotnet run

      - name: Run with time
        run: |
          dotnet run 23